"""upgrade tables

Revision ID: 28f263dc0dca
Revises: e7bb773f98d2
Create Date: 2026-04-23 03:05:01.378605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28f263dc0dca'
down_revision: Union[str, None] = 'e7bb773f98d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verifications', sa.Column('type', sa.String(), nullable=False))
    op.add_column('email_verifications', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.add_column('email_verifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('email_verifications', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verifications', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('email_verifications', 'created_at')
    op.drop_column('email_verifications', 'is_used')
    op.drop_column('email_verifications', 'type')
    # ### end Alembic commands ###
