"""Update department endpoint permissions and fix user_id type in dependencies

Revision ID: b302835e1c1b
Revises: 9ee4687bed02
Create Date: 2026-04-23 22:01:29.708374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b302835e1c1b'
down_revision: Union[str, None] = '9ee4687bed02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
